# BUILD STAGE ###################### 
FROM python:3.13-slim

WORKDIR /pubsub

# Get the uv installer. 
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# COPY THE NEEDED FILES.        
COPY requirements.txt requirements.txt
COPY pub_sub.py pub_sub.py
# TO CAPTURE CONFIG VARS 
COPY configs/configs.py configs/configs.py

# ACTIVATE VENV
RUN uv venv

# INSTALL THE REQUIREMENTS
RUN uv pip install -r requirements.txt

# Creates a temp user for security so container is not run as root. 
RUN useradd --create-home tempuser
USER tempuser

CMD ["uv", "run", "pub_sub.py"]

