FROM python:3.12-slim

WORKDIR /btc_dashboard

# GET THE UV BINARIES
COPY --from=ghcr.io/astral-sh/uv:0.9.21 /uv /uvx /bin/


# GET PROJECT DEPENDENCIES
COPY pyproject.toml pyproject.toml
RUN uv pip install --system -r pyproject.toml

# COPY PROJECT SCRIPTS
COPY . .

# STARTS TEMP USER 
# Added -m to create the home directory /home/tempuser
RUN useradd -m tempuser

# Ensure tempuser owns the working directory as well
RUN chown -R tempuser:tempuser /btc_dashboard

USER tempuser

# OPEN PORT AND START APPLICATION
EXPOSE 8080

# Disable usage statistics to prevent Streamlit from writing to the home folder
ENV STREAMLIT_GATHER_USAGE_STATS=false

# Force Streamlit to use /tmp for its internal configuration
ENV STREAMLIT_CONFIG_DIR=/tmp

ENTRYPOINT ["streamlit", "run", "main.py", "--server.port", "8080", "--server.address", "0.0.0.0"]